### ISSUE TITLE
What happens when rate limit is reached?

### ISSUE THREAD

**Issue by crazy4groovy** [natesilva/p-ratelimit#1]
Hi, I like your lib. However it's not entirely clear what to expect when a rate limit is reached. Does it throw an Error? Silently fail?

**Comment by natesilva** [comment]
The request will be queued in a first-in, first-out queue. If you go over your rate limit, requests will be delayed until they can be run within the limit.

**Comment by natesilva** [comment]
I’ve added a new parameter, `maxDelay`. If your request takes longer than `maxDelay` milliseconds, it will be rejected with `RateLimitTimeoutError`.

If you omit `maxDelay` or set it to `0` your request will be queued for as long as it takes until it can be run within the rate limits.

**Comment by crazy4groovy** [comment]
There is a concern that this could crash a server? If a DOS attack happens, the server will keep queuing the requests? Perhaps a reasonable maxDelay default (eg 2000ms) would be preferred.

**Comment by natesilva** [comment]
If you have something to throttle incoming requests like [limiter](https://github.com/jhurliman/node-rate-limiter), [express-rate-limit](https://github.com/nfriedly/express-rate-limit) or [ratelimiter](https://github.com/tj/node-ratelimiter) etc. you would be protected against that.

This library throttles outgoing requests. For example, if you call [Amazon Web Services](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html) or [Twilio](https://support.twilio.com/hc/en-us/articles/115002943027-Understanding-Twilio-Rate-Limits-and-Message-Queues) you don’t want to exceed your account’s rate limits.
