### ISSUE TITLE
What are defaults?

### ISSUE THREAD

**Issue by mhulse** [natesilva/p-ratelimit#2]
Hi,

Thank you so much for this module! It's great!

I noticed that if I do not pass any options, I get:

```js
TypeError: Cannot read property 'maxDelay' of undefined
```

When I add `maxDelay: 0,`, then my promise map of images downloads instantly and concurrently (with no limiting, from what I can tell).

This seems great, as I'd like the option of not rate limiting by default.

With that said, what are the defaults for the other options? It is looking like `maxDelay` is the only required option, and (based on README) it's default is `0`. Are the others left undefined? From what I can tell, your code doesn't seem to limit anything if `maxDelay` is set.

Thanks again for this rad module... I've spent some time searching for a module that did exactly what `p-ratelimit` does. This is the only module I've found that handles rate limiting this well (IMO).

Thanks!

**Comment by mhulse** [comment]
Just realized that `0` is the default for maxDelay, yet it is a required option.

I don't mind this, just thinking the documentation could be adjusted to clarify defaults and requirements. 👍

**Comment by natesilva** [comment]
It does expect at least an option object to be passed, even if it’s just `{}`. But options should be optional. I’ll support it in the next release.

**Comment by natesilva** [comment]
It’s expected that you’ll specify at least some of the options depending on your needs. There are no defaults, to accommodate various use cases:

* specify `interval` and `rate` for rate limiting
* specify `concurrency` for concurrency limiting
* specify both if you need both rate and concurrency limits

I have a feeling these combinations could be better specified in TypeScript as well. If we support creating a rate limiter without passing options, I’ll need to figure out what defaults make sense. Otherwise I’d probably throw an informative `Error`.

**Comment by mhulse** [comment]
Thank you so much for the clarification/info @natesilva, I really appreciate it!

> - specify interval and rate for rate limiting
> - specify concurrency for concurrency limiting
> - specify both if you need both rate and concurrency limits

^^^ that really helps to clarify things for me, thank you!

Seems like throwing an informative `Error` would suffice.

The way I plan to use this module is via an image downloader module. I'd like to not have any rate or concurrency limiting by default (i.e., pass no options to `p-ratelimit` or just skip using `p-ratelimit` if none of those options are passed).

Otherwise, if a user passes in `interval` and `rate`, or `concurrency`, then the end user can "turn on" those features.

With that said, I wonder if it would also make sense to throw `Error` if `interval` is passed without a `rate` defined? Or, vise versa (`rate` passed without `interval`)?

I would not mind helping with PRs ... I'm just less familiar with TS, so it would be a weekend venture. 👍

**Comment by natesilva** [comment]
The documentation is updated. Hopefully the requirements are clear now.

You can call pRateLimit with no options (`pRateLimit()`) and this works as a no-op, but it prints a warning to the console. To indicate that, yes, you know what you’re doing and really want a no-op, call it like this: `pRateLimit({})`.

Using the `rate` option without `interval`, or vice-versa, now throws an `Error`. I couldn’t figure out how to write a TypeScript interface that enforces this at compile-time. (It’s still okay to omit _both_ `rate` and `interval` if you don’t want rate-limiting; perhaps you only want `concurrency` limits.)

This will be published as 0.10.0 soon.

**Comment by mhulse** [comment]
> This will be published as 0.10.0 soon.

Wow, that is awesome!!!

Thank you so much @natesilva, I really appreciate it!

Have an excellent day!
